### ISSUE TITLE
Working group roadmap 🗺️

### ISSUE THREAD

**Issue by FrancisBanville** [PoisotLab/BiodiversityObservationNetworks.jl#29]
During the spatial metaweb working group meetings, we discussed a roadmap for the package development and writing of the package manuscript. This is what we planned (in chronological order): 

- ~[ ] API simulation to batching~
- [x] v0.1 goes live
- [x] Vignette and documentation
- [ ] Test if having species distributions in estimate is better (since it is already a part of the uncertainty score)
- [x] GEO BON flex
- [ ] Cube algorithm 
- [ ] Trade-offs in temporal sampling (costs)
- [ ] Input layer of the number of unknown interactions (and type ? score ?)
- [ ] Preprint (December 2022) - Methods (Pkg), Ecography (maps)
- [ ] ~Modify simulation so optimization~

We should check off the ones that have already been done, and write the others as individual issues and milestones, when appropriate.

**Comment by gottacatchenall** [comment]
we're getting there, only a couple of years later
